project:
  output-dir: docs
  type: site
site:
  title: testsite
  site-url: https://www.mysite.com/
  google-analytics: UA-20375833-3
  sidebar:
    contents:
    - section: Lubridate 
      href: /lubridate
      contents:
        - text: News
          href: /lubridate/news.md
        - text: Reference
          href: /lubridate/reference
    - section: HMS 
      href: /hms
      contents:
        - text: News
          href: /hms/news.md
        - text: Reference
          href: /hms/reference          
format:
  html:
    toc: true
    code-copy: true
    code-overflow: wrap
